import { ProfileConfig, SkillCategory, ThemeConfig, ThemeId } from "@/types/profile";

export const THEMES: Record<ThemeId, ThemeConfig> = {
  tokyonight: {
    id: "tokyonight",
    name: "Tokyo Night",
    badgeColor: "00F0FF",
    statsTheme: "tokyonight",
    capsuleColors: "0,2,20,40",
    typewriterColor: "00F0FF",
    previewBg: "#0d1117",
  },
  cyberpunk: {
    id: "cyberpunk",
    name: "Cyberpunk Neon",
    badgeColor: "f72585",
    statsTheme: "radical",
    capsuleColors: "10,20,30,40",
    typewriterColor: "7209B7",
    previewBg: "#05050d",
  },
  catppuccin: {
    id: "catppuccin",
    name: "Catppuccin Mocha",
    badgeColor: "cba6f7",
    statsTheme: "catppuccin_mocha",
    capsuleColors: "24,25,30,40",
    typewriterColor: "89B4FA",
    previewBg: "#1e1e2e",
  },
  dracula: {
    id: "dracula",
    name: "Dracula Classic",
    badgeColor: "bd93f9",
    statsTheme: "dracula",
    capsuleColors: "0,1,2,3",
    typewriterColor: "50FA7B",
    previewBg: "#282a36",
  },
  nord: {
    id: "nord",
    name: "Nord Frost",
    badgeColor: "88c0d0",
    statsTheme: "nord",
    capsuleColors: "35,40,45,50",
    typewriterColor: "88C0D0",
    previewBg: "#2e3440",
  },
};

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    title: "AI, Machine Learning & Vision",
    skills: [
      { id: "python", name: "Python" },
      { id: "pytorch", name: "PyTorch" },
      { id: "tensorflow", name: "TensorFlow" },
      { id: "opencv", name: "OpenCV" },
      { id: "scikitlearn", name: "Scikit-Learn" },
    ],
  },
  {
    title: "Frontend & Full-Stack",
    skills: [
      { id: "react", name: "React" },
      { id: "nextjs", name: "Next.js" },
      { id: "typescript", name: "TypeScript" },
      { id: "javascript", name: "JavaScript" },
      { id: "tailwind", name: "TailwindCSS" },
      { id: "html", name: "HTML5" },
      { id: "css", name: "CSS3" },
      { id: "vue", name: "Vue.js" },
    ],
  },
  {
    title: "Backend & Systems",
    skills: [
      { id: "fastapi", name: "FastAPI" },
      { id: "flask", name: "Flask" },
      { id: "nodejs", name: "Node.js" },
      { id: "express", name: "Express" },
      { id: "go", name: "Go" },
      { id: "rust", name: "Rust" },
      { id: "cpp", name: "C++" },
    ],
  },
  {
    title: "Databases & Storage",
    skills: [
      { id: "postgres", name: "PostgreSQL" },
      { id: "mongodb", name: "MongoDB" },
      { id: "mysql", name: "MySQL" },
      { id: "redis", name: "Redis" },
      { id: "supabase", name: "Supabase" },
      { id: "firebase", name: "Firebase" },
    ],
  },
  {
    title: "DevOps, Cloud & Tooling",
    skills: [
      { id: "git", name: "Git" },
      { id: "github", name: "GitHub" },
      { id: "githubactions", name: "GitHub Actions" },
      { id: "docker", name: "Docker" },
      { id: "linux", name: "Linux" },
      { id: "vscode", name: "VS Code" },
      { id: "postman", name: "Postman" },
    ],
  },
];

export const DEFAULT_PROFILE: ProfileConfig = {
  username: "Gaurav1-4",
  displayName: "Gaurav",
  tagline: "AI & Machine Learning Engineer | Computer Vision Specialist",
  typingLines: [
    "AI & Machine Learning Engineer 🤖",
    "Computer Vision & Gesture Control Builder 👁️",
    "Full-Stack Intelligent Systems Architect ⚡",
    "Crafting Next-Gen Interactive AI Applications 🚀",
  ],
  theme: "tokyonight",
  headerType: "waving",
  aboutText: "Building intuitive, high-performance AI and computer vision software from scratch.",
  focus: "AI & Computer Vision",
  location: "India",
  selectedSkills: [
    "python",
    "pytorch",
    "tensorflow",
    "opencv",
    "scikitlearn",
    "react",
    "nextjs",
    "typescript",
    "javascript",
    "tailwind",
    "fastapi",
    "nodejs",
    "git",
    "githubactions",
    "docker",
    "linux",
  ],
  enableSnake: true,
  enable3dGraph: true,
  enableStatsCard: true,
  enableTopLangs: true,
  enableVisitorCounter: true,
  featuredRepos: [
    { name: "air-canvas" },
    { name: "ai-air-tiles" },
    { name: "biology-tutor-app" },
    { name: "air-painter-ai" },
  ],
};
